accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('', views.home, name='home'),
    path('products/', views.products, name='products'),
    path('customer/<str:cus_id>/', views.customer, name='customer'),
    path('create_order/<str:cus_id>', views.create_order, name='create_order'),
    path('update_order/<str:order_id>', views.update_order, name='update_order'),
    path('delete_order/<str:order_id>', views.delete_order, name='delete_order'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register'),
    path('user_page/', views.user_page, name='user_page'),
    path('user_settings', views.user_settings, name='user_settings'),

]

api/urls.py
from django.urls import path
from . import views
# from rest_framework.urlpatterns import format_suffix_patterns


# app_name = 'api'
urlpatterns = [
    path('', views.api_overview, name='api_overview'),
    path('task_list/', views.task_list, name='task_list'),
    path('task_detail/<str:pk>', views.task_detail, name='task_detail'),
    path('task_create/', views.task_create, name='task_create'),
    path('task_update/<str:pk>', views.task_update, name='task_update'),
    path('task_delete/<str:pk>', views.task_delete, name='task_delete'),

]
# urlpatterns = format_suffix_patterns(urlpatterns)

crm1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('api', include('api.urls')),
    path('frontend/', include('frontend.urls')),
    path('', include('learnrest.urls')),
]

urlpatterns += [
    path('api-auth/', include('rest_framework.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Customer(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=200, null=True)
    email = models.EmailField(null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    profile_pic = models.ImageField(default="logo.png", null=True, blank=True)

    def __str__(self):
        return str(self.user)


class Tags(models.Model):
    name = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    CATEGORY = (
        ('Indoor', 'Indoor'),
        ('Out door', 'Out door'),
    )
    name = models.CharField(max_length=200, null=True)
    price = models.FloatField(null=True)
    category = models.CharField(max_length=200, null=True, choices=CATEGORY)
    description = models.CharField(max_length=200, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    tags = models.ManyToManyField(Tags)

    def __str__(self):
        return self.name


class Order(models.Model):
    STATUS = (
        ('Pending', 'Pending'),
        ('Out for delivery', 'Out for delivery'),
        ('Delivered', 'Delivered'),
    )
    customer = models.ForeignKey(Customer, null=True, on_delete=models.SET_NULL)
    product = models.ForeignKey(Product, null=True, on_delete=models.SET_NULL)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    status = models.CharField(max_length=200, null=True, choices=STATUS)

    def __str__(self):
        return self.product.name

accounts/forms.py
from django.forms import ModelForm
from .models import Order, Customer
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = '__all__'


class CreateUserForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())


class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'
        exclude = ['user']

accounts/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.forms import inlineformset_factory
from .decorators import *
from .forms import *
from .models import *


@unauthenticated_user
def register(request):
    form = CreateUserForm

    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')

            messages.success(request, 'Account was created for ' + username)
            return redirect('accounts:login')

    context = {'form': form}
    return render(request, 'accounts/register.html', context)


@unauthenticated_user
def login_page(request):

    form = UserLoginForm
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('accounts:home')
        else:
            messages.info(request, 'Username OR Password is Incorrect')

    context = {'form': form}
    return render(request, 'accounts/login.html', context)


def user_logout(request):
    logout(request)
    return redirect('accounts:login')


@login_required(login_url='accounts:login')
@admin_only
def home(request):
    orders = Order.objects.all()
    customers = Customer.objects.all()

    orders_delivered = orders.filter(status='Delivered').count()
    orders_pending = orders.filter(status='Pending').count()

    context = {
        'orders': orders,
        'customers': customers,
        'orders_delivered': orders_delivered,
        'orders_pending': orders_pending,
    }
    return render(request, 'accounts/dashboard.html', context)


@login_required(login_url='accounts:login')
@admin_only
def products(request):
    products = Product.objects.all()
    context = {'products': products}
    return render(request, 'accounts/products.html', context)


@login_required(login_url='accounts:login')
@admin_only
def customer(request, cus_id):
    customer = get_object_or_404(Customer, pk=cus_id)
    orders = customer.order_set.all()
    # search_filter = OrderFilter()
    # total_orders = orders.customer_set.all().count
    context = {
        'customer': customer,
        'orders': orders,
        # 'search_filter': search_filter,
    }
    return render(request, 'accounts/customer.html', context)


@login_required(login_url='accounts:login')
@admin_only
def create_order(request, cus_id):
    OrderFormSet = inlineformset_factory(Customer, Order, fields=('product', 'status'))
    customer = get_object_or_404(Customer, pk=cus_id)
    formset = OrderFormSet(queryset=Order.objects.none(), instance=customer)
    # form = OrderForm(initial={'customer': customer})
    if request.method == 'POST':
        # form = OrderForm(request.POST)
        formset = OrderFormSet(request.POST, instance=customer)
        if formset.is_valid():
            formset.save()
            return HttpResponseRedirect(reverse('accounts:customer', args=cus_id))
    context = {'formset': formset}
    return render(request, 'accounts/create_order_form.html', context)


@login_required(login_url='accounts:login')
@admin_only
def update_order(request, order_id):
    order = get_object_or_404(Order, pk=order_id)
    form = OrderForm(instance=order)

    if request.method == 'POST':
        form = OrderForm(request.POST, instance=order)
        if form.is_valid():
            form.save()
            return redirect('/')
    context = {'form': form}
    return render(request, 'accounts/create_order_form.html', context)


@login_required(login_url='accounts:login')
@admin_only
def delete_order(request, order_id):
    order = get_object_or_404(Order, pk=order_id)
    if request.method == 'POST':
        order.delete()
        return redirect('/')
    context = {'item': order}
    return render(request, 'accounts/delete_order.html', context)


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['customer'])
def user_page(request):
    orders = request.user.customer.order_set.all()
    orders_delivered = orders.filter(status='Delivered').count()
    orders_pending = orders.filter(status='Pending').count()
    context = {
        'orders': orders,
        'orders_delivered': orders_delivered,
        'orders_pending': orders_pending,
    }
    return render(request, 'accounts/user.html', context)


def user_settings(request):
    customer = request.user.customer
    form = CustomerForm(instance=customer)
    if request.method == 'POST':
        form = CustomerForm(request.POST, request.FILES, instance=customer)
        if form.is_valid():
            form.save()
    context = {'form': form}
    return render(request, 'accounts/user_settings.html', context)

accounts/templates/accounts/create_order_form.html
{% extends 'accounts/main.html' %}
{% block title %} Create Order {% endblock %}

{% block content %}
    <h1>Create Order</h1>
    <form action="" method="post">
        {% csrf_token %}
        {% for form in formset %}
            {{ formset.management_form }}
            {{ formset }}
        {% endfor %}
        <input type="submit" class="btn btn-primary">
    </form>
{% endblock %}

accounts/templates/accounts/customer.html
{% extends 'accounts/main.html' %}
{% block title %}Customer{% endblock %}
{% block content %}

    <br>
    <div class="row">
        <div class="col-md">
            <div class="card card-body">
                <h5>Customer: </h5>
                <hr>
                <a class="btn btn-outline-info btn-sm-btn-block" href="{% url 'accounts:create_order' customer.id%}">Place Order</a><br>
                <a class="btn btn-outline-info btn-sm-btn-block" href="">Update Customer</a><br>
                <a class="btn btn-outline-danger btn-sm-btn-block" href="">Delete Customer</a>
            </div>
        </div>

        <div class="col-md">
            <div class="card card-body">
                <h5>Contact Information: </h5>
                <hr>
                <p>Name: {{ customer.name }}</p>
                <p>Email: {{ customer.email }}</p>
                <p>Phone: {{ customer.phone }}</p>
            </div>
        </div>

        <div class="col-md">
            <div class="card card-body">
                <h5>Total Orders: </h5>
                <hr>
                <h1 style="text-align: center; padding: 10px">{{ orders.count }}</h1>
            </div>
        </div>
    </div>

    <br>
    <div class="row">
        <div class="col">
            <div class="card card-body">
                <form method="post">
                    {{ search_filter.form }}
                    <button class="btn btn-primary" type="submit">Search</button>
                </form>
            </div>
        </div>
    </div>

    <br>
    <div class="row">
        <div class="col">
            <div class="card card-body">
                <table class="table table-sm">
                    <tr>
                        <th>Product</th>
                        <th>Category</th>
                        <th>Date Ordered</th>
                        <th>Status</th>
                        <th>Update</th>
                        <th>Remove</th>
                    </tr>
                    {% for order in orders %}
                    <tr>
                        <td>{{ order.product }}</td>
                        <td>{{ order.product.category }}</td>
                        <td>{{ order.date_created }}</td>
                        <td>{{ order.status }}</td>
                        <td><a class="btn btn-info btn-sm" href="{% url 'accounts:update_order' order.id %}">Update</a></td>
                        <td><a class="btn btn-danger btn-sm" href="{% url 'accounts:delete_order' order.id%}">Remove</a></td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>

{% endblock %}

accounts/templates/accounts/dashboard.html
{% extends 'accounts/main.html' %}
{% block title %}Home{% endblock %}

{% block content %}
{% include 'accounts/status.html' %}
    <br>
    <div class="row">
        <div class="col-md-5">
            <h5>CUSTOMERS:</h5>
            <hr>
            <div class="card card-body">
                <a class="btn btn-primary btn-sm btn-block disable" href="">Create Customer</a>
                <table class="table table-sm">
                    <tr>
                        <th></th>
                        <th>Customer</th>
                        <th>Phone</th>
                    </tr>
                    {% for customer in customers%}
                        <tr>
                            <td><a class="btn btn-info btn-sm" href="{% url 'accounts:customer' customer.id %}">View</a></td>
                            <td>{{ customer.name }}</td>
                            <th>{{ customer.phone }}</th>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>

        <div class="col-md-7">
            <h5>LAST 5 ORDERS</h5>
            <hr>
            <div class="card card-body">

                <table class="table table-sm">
                    <tr>
                        <th>Products</th>
                        <th>Date Orderd</th>
                        <th>Status</th>
                        <th>Update</th>
                        <th>Remove</th>
                    </tr>
                    {% for order in orders%}
                        <tr>
                            <td>{{ order.product }}</td>
                            <td>{{ order.date_created }}</td>
                            <td>{{ order.status }}</td>
                            <td><a class="btn btn-info btn-sm" href="{% url 'accounts:update_order' order.id %}">Update</a></td>
                            <td><a class="btn btn-danger btn-sm" href="{% url 'accounts:delete_order' order.id%}">Remove</a></td>
                        </tr>
                    {% endfor %}

                </table>
            </div>
        </div>
    </div>

{% endblock %}

accounts/templates/accounts/delete_order.html
{% extends 'accounts/main.html' %}
{% block title %}Delete Order{% endblock %}
{% block content %}
    <p>Are you sure you want to delete "{{ item }}"</p>
    <form action="{% url 'accounts:delete_order' item.id %}" method="post">
        {% csrf_token %}
        <a class="btn btn-primary" href="{% url 'accounts:home' %}">Cancel</a>
        <input type="submit" class="btn btn-danger" value="Delete">
    </form>
{% endblock %}

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/bootstrap/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/main.css' %}">
    <script rel="stylesheet" type="text/css" src="{% static 'accounts/js/bootstrap.min.js' %}"></script>
    <script rel="stylesheet" type="text/css" src="{% static 'accounts/js/bootstrap.js' %}"></script>
    <title>Login</title>
</head>
<body>
<h1>Login</h1>
    {% for message in messages %}
        <p class="alert alert-danger">{{ message }}</p>
    {% endfor %}
    <form action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <p>Don't have an account! <a href="{% url 'accounts:register' %}">Register</a></p>
        <input type="submit" class="btn btn-primary" value="Login">
    </form>
</body>
</html>

accounts/templates/accounts/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/bootstrap/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/main.css' %}">
    <script rel="stylesheet" type="text/css" src="{% static 'accounts/js/bootstrap.min.js' %}"></script>
    <script rel="stylesheet" type="text/css" src="{% static 'accounts/js/bootstrap.js' %}"></script>

    <title> {% block title %}CRM{% endblock %}</title>
</head>
<body>
    {% include 'accounts/navbar.html' %}
    {% include 'accounts/navbar.html' %}

    {% block content %}


    {% endblock %}
</body>
</html>

accounts/templates/accounts/navbar.html
{% load static %}
<style>
    #hello-msg{
        font-size: 18px;
        color: slategray;
        margin-right: 20px;
    }
</style>
<nav class="navbar navbar-expand-lg navbar-light bg-light">

    <a class="navbar-brand" href="{% url 'accounts:home' %}">AI WORLD</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarNav" aria-controls="navbarNav" aria-atomic="false"
            aria-label="Toogle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">

        <ul class="navbar-nav">
            {% if request.user.is_staff %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'accounts:home' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:products' %}">Products</a>
                </li>
            {% else %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'accounts:user_settings' %}">Settings <span class="sr-only">Settings</span></a>
                </li>
            {% endif %}
        </ul>
    </div>
    <span id="hello-msg">Hello {{ request.user }}</span>

    <span>
        <a class="btn btn-primary" href="{% url 'accounts:logout' %}">Logout</a>
    </span>

</nav>

accounts/templates/accounts/products.html
{% extends 'accounts/main.html' %}
{% block title %}Products{% endblock %}

{% block content %}
    <br>
    <div class="row">
        <div class="col-md">
            <div class="card card-body">
                <h5>Products</h5>
            </div>
            <div class="card card-body">
                <table class="table">
                    <tr>
                        <th>Product</th>
                        <th>Category</th>
                        <th>Price</th>
                    </tr>
                    {% for product in products %}
                        <tr>
                            <td>{{ product.name }}</td>
                            <td>{{ product.category }}</td>
                            <td>Rs {{ product.price }}</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/bootstrap/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/main.css' %}">
    <script rel="stylesheet" type="text/css" src="{% static 'accounts/js/bootstrap.min.js' %}"></script>
    <script rel="stylesheet" type="text/css" src="{% static 'accounts/js/bootstrap.js' %}"></script>
    <title>Register</title>
</head>
<body>
    <h1>Signup</h1>
    <form action="{% url 'accounts:register' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <p>Already have an account <a href="{% url 'accounts:login' %}">Login!</a></p>
        <input type="submit" class="btn btn-primary" value="Register">
    </form>
</body>
</html>

accounts/templates/accounts/status.html
<br>
<div class="row">
    <div class="col">
        <div class="col-md">
            <div class="card text-center text-white mb-3" id="total-orders">
                <div class="card-header">
                    <h5 class="card-title">Total Orders</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{ orders.count }}</h3>
                </div>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="col-md">
            <div class="card text-center text-white mb-3" id="orders-delivered">
                <div class="card-header">
                    <h5 class="card-title">Orders Delivered</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{ orders_delivered }}</h3>
                </div>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="col-md">
            <div class="card text-center text-white mb-3" id="orders-pending">
                <div class="card-header">
                    <h5 class="card-title">Orders Pending</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{ orders_pending }}</h3>
                </div>
            </div>
        </div>
    </div>
</div>

accounts/templates/accounts/user.html
{% extends 'accounts/main.html' %}
{% block title %}{% endblock %}

{% block content %}
{% include 'accounts/status.html' %}
<div class="row">
        <div class="col">
            <div class="card card-body">
                <table class="table table-sm">
                    <tr>
                        <th>Product</th>
                        <th>Category</th>
                        <th>Date Ordered</th>
                        <th>Status</th>
                    </tr>
                    {% for order in orders %}
                    <tr>
                        <td>{{ order.product }}</td>
                        <td>{{ order.product.category }}</td>
                        <td>{{ order.date_created }}</td>
                        <td>{{ order.status }}</td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>



{% endblock %}

accounts/templates/accounts/user_settings.html
{% extends 'accounts/main.html' %}
{% block title %}Settings{% endblock %}
{% load static %}

{% block content %}

<style>
    .profile-pic{
    max-width: 200px;
    max-height: 200px;
    margin: 0 auto;
    border-radius: 50%;
    }
</style>
<br>
<div class="row">
    <div class="col-md-3">
        <div class="card card-body">
            <a class="btn btn-warning" href="{% url 'accounts:home' %}"> &#8592; Back to Profile</a>
            <hr>
            <h3 style="text-align: center">Account Settings</h3>
            <hr>
            <img class="profile-pic" src="{{ request.user.customer.profile_pic.url }}">
        </div>
    </div>
    <div class="col-md-9">
        <div class="card card-body">
            <form method="POST" action="" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input class="btn btn-primary" type="submit" value="Update Information">
            </form>
        </div>
    </div>
</div>

{% endblock %}